# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: MyMonero
title: MyMonero
email: support@mymonero.com
description: > # this means to ignore newlines until "baseurl:"
  MyMonero is the simplest way to use private digital cash, at the sweet spot between security, convenience, and features.
baseurl: "" # the subpath of your site, e.g. /blog
notification: > 
  The official MyMonero Android app is now live in the Google Play Store. <a href="https://play.google.com/store/apps/details?id=com.mymonero.official_android_application">Check it out here.</a> 
url: "https://mymonero.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
sass:
    sass_dir: assets/_scss
    style: compressed

netlify:
  headers:
    - paths:
        - /*
      headers:
        - "X-Frame-Options: DENY"
        - "X-XSS-Protection: 1; mode=block"
        - "X-Frame-Options: SAMEORIGIN"
        - "Content-Security-Policy: script-src 'self' https://cdn.jsdelivr.net https://netlify-cdp-loader.netlify.app ; object-src 'none'; base-uri 'none';"
        - "Cache-Control: public, max-age=360000"
# Notification var